### ISSUE TITLE
Support for ABBREVIATIONCase

### ISSUE THREAD

**Issue by JonasGruenwald** [lpil/justin#1]
Hey @lpil, not sure if you have time to actively maintain this lib, but I noticed it doesn't support these kinds of cases which I need to handle in a project:

```gleam
  justin.snake_case("DOMDebugger")
  |> should.equal("dom_debugger")
  justin.snake_case("CSSLayerData")
  |> should.equal("css_layer_data")
```

I've made a fork, which handles this case here:
https://github.com/lpil/justin/compare/main...JonasGruenwald:justin:main

But the implementation is kinda wonky, maybe there is a better way?
Also there is some debug printing left in here:
https://github.com/lpil/justin/blob/e51a0a5bb421d0a0906af7051126df88058846bc/src/justin.gleam#L117
which I've removed in my fork.

Is this something you would consider adding to the package?

**Comment by lpil** [comment]
Sounds great! Thank you.

**Comment by JonasGruenwald** [comment]
> Sounds great! Thank you.

Alright sure :) I've made a PR, but as mentioned I'm not sure if the implementation is ideal, let me know if you think I could do something differently.
